/* Auto-generated by build_demo.py — do not edit. */
const DEMO_DATA = {
  search: [
  {
    "id": "bycatch",
    "question": "What are the EU obligations for reducing bycatch in Mediterranean fisheries?",
    "domain": "FISHERIES & MARINE",
    "preloaded": {
      "interpret": {
        "domain": "EU Fisheries Policy — Mediterranean Sea",
        "keyConcepts": [
          "Bycatch reduction",
          "Landing obligation",
          "Selective fishing gear",
          "Mediterranean regulation",
          "Minimum conservation reference sizes"
        ],
        "searchStrategy": "Identify primary CFP legislation, Mediterranean-specific regulations (MedReg), technical measures framework, and relevant STECF scientific advice on selectivity."
      },
      "search": [
        {
          "title": "Regulation (EU) No 1380/2013 — Common Fisheries Policy",
          "celex": "32013R1380",
          "date": "2013-12-28",
          "relevance": "HIGH",
          "reason": "Establishes the landing obligation (discard ban) — the primary EU instrument addressing bycatch."
        },
        {
          "title": "Regulation (EU) 2019/1241 — Technical Measures Framework",
          "celex": "32019R1241",
          "date": "2019-07-25",
          "relevance": "HIGH",
          "reason": "Sets gear specifications, mesh sizes, closed areas, and selectivity requirements directly targeting bycatch reduction."
        },
        {
          "title": "Regulation (EU) 2019/982 — Western Mediterranean MAP",
          "celex": "32019R0982",
          "date": "2019-06-20",
          "relevance": "HIGH",
          "reason": "Multiannual plan for demersal stocks — includes effort reduction and bycatch provisions specific to the Western Med."
        },
        {
          "title": "Regulation (EC) No 1967/2006 — Mediterranean Regulation",
          "celex": "32006R1967",
          "date": "2006-12-21",
          "relevance": "MEDIUM",
          "reason": "Predecessor framework with Med-specific gear restrictions and habitat protections. Partially superseded but still relevant for trawl specifications."
        },
        {
          "title": "STECF EWG Reports on Mediterranean Selectivity",
          "celex": null,
          "date": "2023-01-01",
          "relevance": "MEDIUM",
          "reason": "Scientific basis for bycatch reduction — gear trials, survival rate studies, exemption evaluations."
        },
        {
          "title": "EU Biodiversity Strategy 2030 & Action Plan for Bycatch",
          "celex": "52020DC0380",
          "date": "2020-05-20",
          "relevance": "MEDIUM",
          "reason": "Targets bycatch of sensitive species (seabirds, marine mammals, turtles) beyond commercial fish."
        }
      ],
      "decode": [
        {
          "regulation": "CFP — Landing Obligation (Art. 15, Reg. 1380/2013)",
          "celex": "32013R1380",
          "who": [
            "All EU fishing vessels in the Mediterranean",
            "Member States (monitoring & enforcement)",
            "Regional Advisory Councils (MEDAC)"
          ],
          "what": "All catches of species subject to catch limits or minimum sizes must be landed and counted against quotas. De minimis exemptions allowed up to 5% if selectivity is very difficult to improve or handling costs are disproportionate. High survivability exemptions for species with demonstrated post-release survival.",
          "keyObligations": [
            "Retain and land all regulated species catches",
            "Record and report all catches including below-MCRS fish",
            "Undersized fish restricted to non-human consumption (fishmeal, pet food)",
            "Gradually phase in by species group (completed 2019)"
          ]
        },
        {
          "regulation": "Technical Measures (Reg. 2019/1241)",
          "celex": "32019R1241",
          "who": [
            "Vessel operators using towed gear in the Med",
            "National authorities (gear inspections)",
            "Gear manufacturers"
          ],
          "what": "Establishes minimum mesh sizes (40mm square / 50mm diamond for demersal trawls in the Med), mandatory selectivity devices (sorting grids, escape panels), closed areas and seasonal closures to protect juveniles and spawning aggregations, and restrictions on gear types near sensitive habitats.",
          "keyObligations": [
            "Minimum 40mm square-mesh or 50mm diamond-mesh for demersal trawls",
            "Mandatory square-mesh panels or sorting grids in specific fisheries",
            "Prohibition of trawling within 3 nautical miles of coast or 50m depth (whichever is closer)",
            "Seasonal closures for juvenile and spawning protection"
          ]
        },
        {
          "regulation": "Western Mediterranean MAP (Reg. 2019/982)",
          "celex": "32019R0982",
          "who": [
            "Trawl fleets in GSAs 1-7 (Western Med)",
            "Spanish, French, Italian fleets primarily",
            "STECF (annual stock assessment)"
          ],
          "what": "Reduces fishing effort (days at sea) for demersal trawlers by 40% over 5 years (2020-2024), with annual 7.5% cuts as default. Aims to reach MSY for key demersal stocks. Bycatch addressed through effort reduction (less time fishing = less bycatch) rather than gear-specific mandates.",
          "keyObligations": [
            "Maximum fishing days reduced annually",
            "Effort baseline set from 2015-2017 reference period",
            "Closure of areas identified as nursery or spawning grounds",
            "Mandatory vessel monitoring (VMS) for all trawlers"
          ]
        }
      ],
      "deepDive": {
        "interactions": [
          {
            "issue": "Landing Obligation vs. Mediterranean Reality",
            "detail": "The landing obligation was designed for North Sea/Atlantic single-species fisheries. Mediterranean fisheries catch 50+ species per haul. Implementing a discard ban in a hyper-mixed fishery creates massive practical problems — storage space, sorting time, port infrastructure. De minimis exemptions are the pressure valve, but they partially defeat the purpose."
          },
          {
            "issue": "Effort Reduction vs. Selectivity Investment",
            "detail": "The WestMed MAP cuts fishing days, which reduces bycatch mechanically (less time at sea). But this disincentivises investment in better gear selectivity — why spend EUR 50K on a sorting grid if you're losing fishing days anyway? The two policy instruments pull in opposite directions on fisher behaviour."
          },
          {
            "issue": "Technical Measures vs. Fleet Diversity",
            "detail": "Uniform mesh size rules struggle with Mediterranean fleet diversity. A 40mm mesh that works for a large trawler may be impractical for a small-scale vessel targeting different species. One-size-fits-all technical measures often become one-size-fits-none."
          }
        ],
        "gaps": [
          {
            "gap": "Sensitive Species Bycatch",
            "detail": "The CFP and technical measures focus on commercial fish bycatch. Bycatch of seabirds, sea turtles, dolphins, and sharks is addressed more weakly — mainly through the Habitats Directive and a 2023 EU Action Plan that remains largely non-binding for fisheries."
          },
          {
            "gap": "Small-Scale Fleet Coverage",
            "detail": "Vessels under 12m are exempt from many reporting requirements and some gear regulations. Yet small-scale fleets collectively account for significant bycatch, particularly in coastal nursery areas. The regulatory blind spot is substantial."
          },
          {
            "gap": "Monitoring & Enforcement",
            "detail": "Observer coverage in the Mediterranean is extremely low (less than 1% of trips in many fisheries). Without at-sea monitoring, compliance with the landing obligation and gear regulations is essentially unverifiable. Electronic monitoring (CCTV) is discussed but not mandated."
          }
        ],
        "stakeholders": [
          {
            "group": "Large demersal trawlers",
            "impact": "DOUBLE BURDEN",
            "detail": "Hit by both effort reductions (WestMed MAP) and gear requirements (Tech Measures). Facing 40% effort cuts while being asked to invest in selectivity. Many questioning fleet viability."
          },
          {
            "group": "Small-scale coastal fishers",
            "impact": "PARTIALLY EXEMPT BUT SQUEEZED",
            "detail": "Fewer direct regulatory obligations, but declining stocks (partly from trawl bycatch) reduce their catches too. Bear the ecological costs of industrial bycatch without causing most of it."
          },
          {
            "group": "Mediterranean Member States",
            "impact": "IMPLEMENTATION CHALLENGE",
            "detail": "Spain, France, Italy, Greece must enforce complex overlapping regulations with limited inspection capacity. Political pressure from fishing communities creates enforcement gaps."
          },
          {
            "group": "Marine ecosystems",
            "impact": "SLOW IMPROVEMENT",
            "detail": "Some evidence of stock recovery in Western Med demersal fisheries post-2020 effort cuts. But bycatch of sensitive species, habitat damage from bottom trawling, and juvenile mortality remain high."
          }
        ]
      },
      "briefing": "EU obligations for Mediterranean bycatch reduction operate through three layered instruments that don't always cohere. The landing obligation (CFP) bans discards but collides with the hyper-mixed nature of Med fisheries. Technical measures set gear specifications but struggle with fleet diversity. The Western Mediterranean MAP cuts effort — effective but blunt, and it may actually discourage selectivity investment.\n\nThe critical gaps are in monitoring (observer coverage near zero), small-scale fleet coverage (largely exempt from reporting), and sensitive species bycatch (addressed by separate, weaker instruments). For the Mediterranean, the fundamental tension is that regulations designed for data-rich, single-species Northern European fisheries have been layered onto a data-poor, multi-species, multi-gear system.\n\nThe most impactful reform would be mandatory electronic monitoring — without it, compliance is aspirational. Watch for: the WestMed MAP evaluation (post-2024), expansion of effort regimes to the Eastern/Central Med, and whether the EU Bycatch Action Plan gets binding force."
    }
  },
  {
    "id": "ai_hiring",
    "question": "Can EU employers legally use AI to screen job applicants?",
    "domain": "DIGITAL & EMPLOYMENT",
    "preloaded": {
      "interpret": {
        "domain": "EU AI Regulation — Employment & Recruitment",
        "keyConcepts": [
          "AI in recruitment",
          "High-risk AI systems",
          "Automated decision-making",
          "Employment discrimination",
          "GDPR Article 22"
        ],
        "searchStrategy": "Cross-reference AI Act provisions on employment (high-risk category), GDPR automated decision-making rules, EU anti-discrimination directives, and emerging national guidance on algorithmic hiring."
      },
      "search": [
        {
          "title": "Regulation (EU) 2024/1689 — AI Act",
          "celex": "32024R1689",
          "date": "2024-07-12",
          "relevance": "HIGH",
          "reason": "Classifies AI systems for recruitment and worker management as HIGH-RISK. Core regulatory framework."
        },
        {
          "title": "GDPR (Regulation 2016/679) — Article 22",
          "celex": "32016R0679",
          "date": "2016-05-04",
          "relevance": "HIGH",
          "reason": "Right not to be subject to purely automated decisions with legal or significant effects. Directly applies to AI hiring tools."
        },
        {
          "title": "Directive 2000/78/EC — Equal Treatment in Employment",
          "celex": "32000L0078",
          "date": "2000-11-27",
          "relevance": "HIGH",
          "reason": "Prohibits discrimination on grounds of religion, disability, age, sexual orientation. AI screening must comply."
        },
        {
          "title": "Directive 2006/54/EC — Gender Equality in Employment",
          "celex": "32006L0054",
          "date": "2006-07-05",
          "relevance": "MEDIUM",
          "reason": "Prohibits sex discrimination in access to employment. AI tools trained on historical data risk perpetuating gender bias."
        },
        {
          "title": "Proposed AI Liability Directive",
          "celex": null,
          "date": "2022-09-28",
          "relevance": "MEDIUM",
          "reason": "Would shift burden of proof to AI providers when AI causes harm — relevant for rejected applicants challenging AI screening."
        }
      ],
      "decode": [
        {
          "regulation": "AI Act — High-Risk Classification (Annex III, Point 4)",
          "celex": "32024R1689",
          "who": [
            "Employers deploying AI screening tools",
            "HR technology providers",
            "National market surveillance authorities",
            "Job applicants"
          ],
          "what": "AI systems intended for recruitment, screening, filtering, or evaluating candidates are classified as HIGH-RISK. Providers must meet strict pre-market requirements: risk management system, data quality standards, technical documentation, transparency, human oversight, accuracy testing, and bias monitoring.",
          "keyObligations": [
            "Mandatory conformity assessment before market placement",
            "Bias testing and monitoring across protected characteristics",
            "Transparent notification to candidates that AI is being used",
            "Meaningful human oversight — human must be able to override AI decisions",
            "Logging of all AI-assisted decisions for auditability"
          ]
        },
        {
          "regulation": "GDPR — Article 22 (Automated Decision-Making)",
          "celex": "32016R0679",
          "who": [
            "Any data controller using automated processing",
            "Job applicants as data subjects",
            "National data protection authorities"
          ],
          "what": "Data subjects have the right not to be subject to decisions based solely on automated processing that produce legal or similarly significant effects. Hiring decisions clearly qualify. Exceptions exist but additional safeguards are always required.",
          "keyObligations": [
            "Cannot make hiring decisions based solely on automated processing without explicit legal basis",
            "Must inform applicants about the logic involved and consequences",
            "Must provide mechanism to contest automated decisions and obtain human review",
            "Data Protection Impact Assessment (DPIA) required before deployment"
          ]
        },
        {
          "regulation": "Equal Treatment Directives (2000/78/EC & 2006/54/EC)",
          "celex": "32000L0078",
          "who": [
            "All EU employers",
            "AI tool providers indirectly",
            "Equality bodies in Member States"
          ],
          "what": "Prohibit direct and indirect discrimination in employment. AI screening tools that produce disparate impact on protected groups constitute indirect discrimination unless objectively justified.",
          "keyObligations": [
            "AI screening must not produce unjustified disparate impact on protected groups",
            "Employer bears burden of proving non-discrimination once prima facie case shown",
            "Applies to all stages: CV screening, video interviews, aptitude assessments",
            "Reasonable accommodations for disability must be possible even in automated systems"
          ]
        }
      ],
      "deepDive": {
        "interactions": [
          {
            "issue": "AI Act + GDPR: Cumulative Compliance Burden",
            "detail": "Employers must simultaneously satisfy AI Act high-risk requirements AND GDPR Article 22 safeguards. These overlap but don't align perfectly — different transparency obligations, different impact assessments (FRIA vs DPIA), different supervisory authorities."
          },
          {
            "issue": "Human Oversight Paradox",
            "detail": "Both AI Act and GDPR require meaningful human oversight. But if a human rubber-stamps AI recommendations (as commonly happens), the oversight is illusory. If the human re-evaluates every candidate, the efficiency gains disappear. The regulations demand a middle ground that is poorly defined."
          },
          {
            "issue": "Bias Testing vs. Data Protection",
            "detail": "The AI Act requires testing for bias across protected characteristics (race, gender, disability). But collecting this sensitive data may itself violate GDPR's restrictions on special category data. A genuine catch-22."
          }
        ],
        "gaps": [
          {
            "gap": "Emotional/Personality AI",
            "detail": "AI tools assessing personality or emotional state from video interviews are problematic. The AI Act bans emotion recognition in some workplace contexts but boundaries are unclear for recruitment. These tools' validity is scientifically contested yet widely marketed."
          },
          {
            "gap": "Cross-Border Recruitment",
            "detail": "An employer using a US-built AI tool to screen candidates across the EU faces divergent national implementations of all three regulatory layers. No centralised EU enforcement mechanism exists yet."
          },
          {
            "gap": "Candidate Redress",
            "detail": "Rejected candidates typically don't know AI was involved. The practical ability to challenge AI-assisted hiring decisions remains weak despite strong rights on paper."
          }
        ],
        "stakeholders": [
          {
            "group": "Large employers",
            "impact": "COMPLIANCE INVESTMENT",
            "detail": "Resources to implement AI governance frameworks. May gain advantage over smaller competitors who can't afford compliant AI hiring."
          },
          {
            "group": "HR tech vendors",
            "impact": "MARKET RESTRUCTURING",
            "detail": "Conformity assessment costs will push out smaller players. US vendors must adapt products for EU market or exit."
          },
          {
            "group": "Job applicants",
            "impact": "STRONG RIGHTS, WEAK ENFORCEMENT",
            "detail": "Extensive protections on paper. In practice, opacity means most applicants won't know how AI was used."
          },
          {
            "group": "SMEs",
            "impact": "SQUEEZED OUT OF AI HIRING",
            "detail": "Compliance costs may deter SMEs entirely. Regulation intended to protect applicants may concentrate AI power in large organisations."
          }
        ]
      },
      "briefing": "EU employers can legally use AI to screen applicants — but only under stringent conditions that most current deployments probably don't meet. The AI Act classifies recruitment AI as high-risk, requiring conformity assessment, bias monitoring, transparency, and meaningful human oversight. GDPR Article 22 independently requires a legal basis for automated decisions, applicant notification, and the right to human review.\n\nThe practical challenges are significant. The human oversight requirement creates a paradox between genuine review and efficiency. Bias testing collides with data protection rules on sensitive data. Cross-border enforcement is fragmented.\n\nThe strongest advice for EU employers today: assume your AI hiring tool is non-compliant unless you've specifically verified it against all three regulatory layers. The AI Act high-risk obligations apply from August 2026. Watch for: national enforcement divergence, the AI Liability Directive's progress, and the first high-profile action against an AI hiring tool."
    }
  },
  {
    "id": "green_transition",
    "question": "How does the EU plan to ensure the green transition doesn't increase energy poverty?",
    "domain": "CLIMATE & SOCIAL POLICY",
    "preloaded": {
      "interpret": {
        "domain": "EU Climate & Social Policy intersection",
        "keyConcepts": [
          "Energy poverty",
          "Just transition",
          "Social Climate Fund",
          "Carbon pricing impacts",
          "Vulnerable households",
          "ETS2"
        ],
        "searchStrategy": "Map the intersection between climate legislation (ETS, Fit for 55) and social protection instruments. Identify mechanisms specifically designed to shield vulnerable groups from transition costs."
      },
      "search": [
        {
          "title": "Regulation (EU) 2023/955 — Social Climate Fund",
          "celex": "32023R0955",
          "date": "2023-05-10",
          "relevance": "HIGH",
          "reason": "Dedicated instrument to address energy and transport poverty from carbon pricing. EUR 65bn over 2026-2032."
        },
        {
          "title": "Directive (EU) 2023/959 — ETS2 (Buildings & Road Transport)",
          "celex": "32023L0959",
          "date": "2023-05-10",
          "relevance": "HIGH",
          "reason": "New carbon pricing for heating and transport — the mechanism that risks increasing energy costs."
        },
        {
          "title": "Directive (EU) 2023/1791 — Energy Efficiency Directive (recast)",
          "celex": "32023L1791",
          "date": "2023-09-13",
          "relevance": "HIGH",
          "reason": "Energy poverty provisions: Member States must prioritise energy-poor households in efficiency programmes."
        },
        {
          "title": "Commission Recommendation on Energy Poverty (2020/1563)",
          "celex": "32020H1563",
          "date": "2020-10-14",
          "relevance": "MEDIUM",
          "reason": "Non-binding guidance on energy poverty indicators and national approaches."
        },
        {
          "title": "Just Transition Mechanism (Reg. 2021/1056)",
          "celex": "32021R1056",
          "date": "2021-06-24",
          "relevance": "MEDIUM",
          "reason": "Supports fossil-fuel dependent regions — community-level poverty risk, not household energy costs directly."
        }
      ],
      "decode": [
        {
          "regulation": "Social Climate Fund (Reg. 2023/955)",
          "celex": "32023R0955",
          "who": [
            "Vulnerable households in energy poverty",
            "Vulnerable micro-enterprises",
            "Vulnerable transport users",
            "Member States (plan design)"
          ],
          "what": "EUR 65 billion fund (2026-2032) financed by ETS2 auction revenues. Member States submit Social Climate Plans detailing support for vulnerable groups. Can fund renovations, clean heating, public transport, and temporary direct income support.",
          "keyObligations": [
            "Each Member State must submit a Social Climate Plan by June 2025",
            "Plans must identify and quantify vulnerable populations",
            "At least 37.5% on measures with lasting structural impact",
            "Direct income support limited to 37.5% and must decrease over time",
            "National co-financing of 25% required"
          ]
        },
        {
          "regulation": "ETS2 — Buildings & Transport Emissions Trading",
          "celex": "32023L0959",
          "who": [
            "Fuel suppliers (compliance entities)",
            "All households using fossil heating or petrol/diesel",
            "Vulnerable groups (disproportionate impact)"
          ],
          "what": "Extends carbon pricing to building heating and road transport from 2027. Fuel suppliers buy allowances, passing costs to consumers. Price cap at EUR 45; emergency brake if energy prices are exceptionally high.",
          "keyObligations": [
            "Carbon price applied at fuel supplier level from 2027",
            "Expected to add EUR 0.10-0.15 per litre initially",
            "Price stability mechanism at EUR 45",
            "Emergency delay clause linked to energy prices",
            "Auction revenues partially fund Social Climate Fund"
          ]
        },
        {
          "regulation": "Energy Efficiency Directive — Energy Poverty Provisions",
          "celex": "32023L1791",
          "who": [
            "Member States",
            "Energy companies",
            "Energy-poor households"
          ],
          "what": "Requires Member States to prioritise energy-poor households in efficiency schemes. Mandates national definitions of energy poverty and reporting.",
          "keyObligations": [
            "Member States must define energy poverty in national law",
            "Efficiency schemes must deliver savings to energy-poor households",
            "One-stop renovation shops must prioritise vulnerable groups",
            "Annual reporting on energy poverty levels"
          ]
        }
      ],
      "deepDive": {
        "interactions": [
          {
            "issue": "Social Climate Fund Timing vs. ETS2 Impact",
            "detail": "The Fund starts in 2026 but renovations take years. ETS2 costs hit immediately in 2027. Structural timing mismatch — costs arrive before investments pay off. Direct income support is capped and must decrease."
          },
          {
            "issue": "Definition Fragmentation",
            "detail": "Each Member State defines energy poverty differently. Some use income thresholds, others expenditure shares, others self-reported inability to heat. Without common definition, the Social Climate Fund risks inconsistent targeting."
          },
          {
            "issue": "Renovation Paradox",
            "detail": "The most energy-poor live in the worst buildings — hardest and most expensive to renovate. Efficiency programmes tend to reach middle-income homeowners first. Without explicit mechanisms, the hardest-to-reach remain hardest-to-reach."
          }
        ],
        "gaps": [
          {
            "gap": "Renters vs. Owners (Split Incentive)",
            "detail": "Landlords invest in renovation, tenants benefit from lower bills. Neither has sufficient incentive alone. The Fund acknowledges this but solutions require national tenancy law reform the EU can't mandate."
          },
          {
            "gap": "Rural Transport Poverty",
            "detail": "ETS2 raises fuel costs. Rural populations have no public transport alternative and can't afford EVs. The Fund can support public transport but that helps urban areas disproportionately."
          },
          {
            "gap": "Scale vs. Problem",
            "detail": "EUR 65bn over 7 years across 27 states averages roughly EUR 340M per country per year. With 50M+ energy-poor Europeans, that's approximately EUR 50 per person per year before admin costs."
          }
        ],
        "stakeholders": [
          {
            "group": "Energy-poor households (50M+ Europeans)",
            "impact": "HELP COMING, BUT LATE AND SMALL",
            "detail": "Higher costs from 2027. Fund provides some buffer but structural investments take years. Net effect uncertain — depends on national plan quality."
          },
          {
            "group": "Rural communities",
            "impact": "DOUBLE EXPOSURE",
            "detail": "Higher transport costs (fuel-dependent, no alternatives) plus higher heating costs (older housing). Least likely to benefit from urban-focused solutions."
          },
          {
            "group": "High energy poverty Member States",
            "impact": "CAPACITY CHALLENGE",
            "detail": "Bulgaria, Greece, Lithuania, Portugal have highest rates but lower administrative capacity. 25% co-financing adds fiscal pressure."
          },
          {
            "group": "Building/renovation sector",
            "impact": "DEMAND SURGE COMING",
            "detail": "Massive renovation demand expected. Workforce shortages acute. Risk of cost inflation eroding public funding value."
          }
        ]
      },
      "briefing": "The EU has built a three-part architecture: the Social Climate Fund provides targeted support, ETS2 includes price stability and delay mechanisms, and the Energy Efficiency Directive mandates prioritising vulnerable households. On paper, this is the most comprehensive global attempt to pair climate ambition with social protection.\n\nIn practice, three structural problems threaten delivery. First, timing: carbon costs arrive in 2027 but renovation benefits materialise years later. Second, scale: EUR 65bn spread across 27 countries and 50M+ energy-poor citizens is supplementary at best. Third, targeting: without a common EU definition of energy poverty and with deep split-incentive problems in rental housing, the money may not reach those who need it most.\n\nThe politically sensitive truth: for the most vulnerable, the transition will likely get worse before it gets better. The Social Climate Fund buys political legitimacy for ETS2 but may not buy enough actual protection. Watch for: Social Climate Plan quality (mid-2025), whether the ETS2 emergency brake triggers, renovation workforce bottlenecks, and the first political backlash when fuel prices rise in 2027."
    }
  }
],
  analyse: [
  {
    "id": "cfp",
    "title": "Common Fisheries Policy (Reg. 1380/2013)",
    "domain": "FISHERIES & MARINE",
    "classification": "EU REGULATION",
    "preloaded": {
      "decode": {
        "who": [
          "EU fishing fleet operators and vessel owners",
          "Member State fisheries administrations",
          "Regional Advisory Councils (RACs / ACs)",
          "European Commission (DG MARE)",
          "Aquaculture producers"
        ],
        "what": "The Common Fisheries Policy is the EU's primary framework for managing marine biological resources and fisheries. It establishes the principles of maximum sustainable yield (MSY), the landing obligation (discard ban), fleet capacity ceilings, multiannual management plans, and a regionalisation mechanism that delegates certain management decisions to groups of Member States with a direct interest. The regulation replaced the previous CFP (Reg. 2371/2002) following a comprehensive reform process that began in 2009.",
        "scope": "Applies to the conservation of marine biological resources and the management of fisheries and fleets exploiting such resources. Covers all fishing activities by EU vessels regardless of waters fished, and all fishing activities in EU waters by any vessel. Also covers aquaculture and the processing and marketing of fishery and aquaculture products where these activities take place on the territory of Member States or in EU waters.",
        "keyDefinitions": [
          {
            "term": "Maximum Sustainable Yield (MSY)",
            "definition": "The largest catch that can be taken from a fish stock indefinitely without damaging its ability to reproduce. The CFP requires all stocks to be fished at or below MSY levels."
          },
          {
            "term": "Landing Obligation",
            "definition": "The requirement to retain on board, land, and count against quotas all catches of species subject to catch limits or minimum sizes. Effectively a discard ban, phased in between 2015 and 2019."
          },
          {
            "term": "Minimum Conservation Reference Size (MCRS)",
            "definition": "The minimum size below which fish must still be landed (under the landing obligation) but cannot be sold for direct human consumption. Replaces the old concept of Minimum Landing Size (MLS)."
          },
          {
            "term": "Total Allowable Catch (TAC)",
            "definition": "The maximum quantity of a specific fish stock that can be caught in a given period, set annually by the Council of Ministers based on scientific advice from ICES and STECF."
          },
          {
            "term": "Regionalisation",
            "definition": "A governance mechanism allowing Member States with a direct management interest in a sea basin to submit joint recommendations for conservation measures, which the Commission can adopt as delegated acts."
          },
          {
            "term": "Fleet Capacity Ceiling",
            "definition": "A fixed maximum for each Member State's fishing fleet measured in gross tonnage (GT) and engine power (kW). New capacity can only enter the fleet if equivalent capacity is removed."
          }
        ]
      },
      "timeline": [
        {
          "date": "2009",
          "event": "Commission Green Paper launches CFP reform process",
          "type": "milestone"
        },
        {
          "date": "2011-07",
          "event": "Commission proposal for new CFP regulation (COM(2011) 425)",
          "type": "milestone"
        },
        {
          "date": "2013-12-11",
          "event": "Regulation 1380/2013 adopted and enters into force",
          "type": "milestone"
        },
        {
          "date": "2015-01-01",
          "event": "Landing obligation begins for pelagic fisheries and Baltic cod",
          "type": "obligation"
        },
        {
          "date": "2017-01-01",
          "event": "Landing obligation extended to key demersal species in the North Sea and Atlantic",
          "type": "obligation"
        },
        {
          "date": "2019-01-01",
          "event": "Full landing obligation in force for all TAC-regulated species",
          "type": "deadline"
        },
        {
          "date": "2020",
          "event": "MSY target date — all stocks to be fished at or below MSY",
          "type": "deadline"
        },
        {
          "date": "2022",
          "event": "Commission evaluation report on CFP implementation (COM(2022) 253)",
          "type": "milestone"
        }
      ],
      "deepDive": {
        "ambiguities": [
          {
            "text": "where possible and practicable",
            "analysis": "Used repeatedly in the context of achieving MSY. This qualifier allows indefinite delays — the 2020 MSY deadline was missed for numerous stocks because Member States argued it was not 'practicable' given socio-economic impacts. No criteria define when something crosses from impracticable to mandatory."
          },
          {
            "text": "best available scientific advice",
            "analysis": "The regulation requires management to be based on 'best available scientific advice' but does not define what qualifies. When ICES and STECF disagree, or when Member States commission alternative studies, the concept becomes a vehicle for cherry-picking science to support political TAC decisions."
          },
          {
            "text": "demonstrated high survivability",
            "analysis": "Exemption from the landing obligation for species with 'high survivability' is scientifically logical but thresholds are undefined. What survival rate qualifies? 50%? 80%? The ambiguity has allowed broad exemption claims with varying evidentiary standards across sea basins."
          },
          {
            "text": "disproportionate costs of handling unwanted catches",
            "analysis": "De minimis exemptions from the landing obligation are allowed where handling costs are 'disproportionate.' Disproportionate to what? Fleet revenue? Fish value? The comparison baseline is unstated, enabling elastic interpretation of what the exemption covers."
          }
        ],
        "contradictions": [
          {
            "issue": "MSY Target vs. Mixed-Fishery Reality",
            "detail": "Article 2(2) requires all stocks to be fished at MSY. But mixed fisheries catch multiple species simultaneously. In a mixed trawl haul, achieving MSY for one stock may require overfishing another (the 'choke species' problem). The regulation mandates an outcome that is physically impossible in many fisheries without fundamentally changing gear or abandoning certain fishing grounds."
          },
          {
            "issue": "Landing Obligation vs. Quota System Architecture",
            "detail": "The landing obligation requires all regulated catches to be landed and counted against quotas. But the TAC/quota system was designed assuming discards. When fishers must land fish they previously discarded, quotas are exhausted earlier, creating premature fishery closures (choke situations). The discard ban was layered onto a quota system that assumed discarding."
          },
          {
            "issue": "Regionalisation vs. Level Playing Field",
            "detail": "Regionalisation empowers Member State groups to set tailored conservation measures. But different rules in adjacent sea basins for the same species create unequal competitive conditions. A French trawler in the Celtic Sea may face different selectivity rules than a Spanish trawler targeting the same stock in the Bay of Biscay."
          }
        ],
        "stakeholderImpacts": [
          {
            "group": "Large-scale industrial fleet",
            "impact": "CAPACITY CONSTRAINED",
            "detail": "Fleet capacity ceilings prevent expansion. The landing obligation increases operational costs (sorting, storage, landing infrastructure). MSY targets reduce available quota. Combined effect: declining profitability for vessels that cannot adapt fishing patterns."
          },
          {
            "group": "Small-scale coastal fishers",
            "impact": "FORMALLY PRIORITISED, PRACTICALLY MARGINALISED",
            "detail": "Article 17 requires Member States to use transparent and objective criteria including social and environmental ones when allocating fishing opportunities. In practice, historical catch records dominate allocation, perpetuating the advantage of industrial fleets. The small-scale priority is aspirational."
          },
          {
            "group": "EU aquaculture sector",
            "impact": "UNDERSERVED BY FRAMEWORK",
            "detail": "Despite Title V (Articles 34-36) establishing aquaculture strategic guidelines, the CFP remains overwhelmingly focused on wild-capture fisheries. Aquaculture producers receive policy attention but limited concrete regulatory support for growth barriers like licensing complexity."
          },
          {
            "group": "Fisheries scientists (ICES, STECF)",
            "impact": "INFLUENCE CEILING",
            "detail": "Scientific advice is mandatory but not binding. The Council routinely sets TACs above ICES advice — by an average of 20% in the North-East Atlantic. The science-policy interface is structured to consult science, not follow it."
          },
          {
            "group": "Third-country fleets (e.g., UK post-Brexit)",
            "impact": "DISRUPTED ACCESS",
            "detail": "The CFP's external dimension governs access agreements and shared-stock management. Brexit removed the UK from the CFP, converting internal management of shared stocks into bilateral negotiations — increasing uncertainty for all parties."
          }
        ],
        "crossReferences": [
          {
            "regulation": "Regulation (EU) 2019/1241 — Technical Measures Framework",
            "relation": "Specifies the gear, mesh sizes, closed areas, and selectivity devices that implement the CFP's conservation objectives. Directly operationalises the landing obligation and MSY targets set by the CFP."
          },
          {
            "regulation": "Regulation (EC) No 1224/2009 — Control Regulation",
            "relation": "The enforcement backbone of the CFP. Establishes monitoring, inspection, and sanction rules including VMS, logbooks, landing declarations, and the points system for serious infringements."
          },
          {
            "regulation": "Regulation (EU) 2017/1004 — Data Collection Framework (DCF)",
            "relation": "Requires Member States to collect biological, economic, and environmental fisheries data. Underpins the 'best available scientific advice' on which CFP management decisions must be based."
          },
          {
            "regulation": "Directive 2008/56/EC — Marine Strategy Framework Directive (MSFD)",
            "relation": "Requires Good Environmental Status (GES) in EU marine waters by 2020. Descriptor 3 (commercial fish populations) directly links to CFP MSY targets. The two frameworks share objectives but have different governance structures."
          },
          {
            "regulation": "Regulation (EU) 2023/2842 — Revised Control Regulation",
            "relation": "Major update to the 2009 Control Regulation, introducing mandatory CCTV for certain vessels, digital catch reporting, and strengthened traceability. Addresses long-standing enforcement gaps in the landing obligation."
          }
        ],
        "newVsInherited": [
          {
            "element": "Landing Obligation (Art. 15)",
            "status": "NEW",
            "note": "The discard ban was the flagship reform of the 2013 CFP. No predecessor framework required landing of all regulated catches. Represents a fundamental shift in fisheries management philosophy."
          },
          {
            "element": "MSY as Binding Target (Art. 2(2))",
            "status": "STRENGTHENED",
            "note": "MSY existed as a goal in the 2002 CFP but was aspirational. Reg. 1380/2013 made it a legally binding target with a 2020 deadline, shifting it from policy aspiration to legal obligation."
          },
          {
            "element": "TAC/Quota System (Art. 16-17)",
            "status": "INHERITED",
            "note": "The TAC and quota allocation system has been the core of the CFP since the 1983 regulation. Relative stability (fixed national shares) dates to 1983 and was carried forward unchanged."
          },
          {
            "element": "Regionalisation (Art. 18)",
            "status": "NEW",
            "note": "The mechanism for Member State groups to submit joint recommendations was entirely new. Previous CFPs were centrally managed with limited regional input. This was a direct response to criticism of Brussels micro-managing diverse fisheries."
          },
          {
            "element": "Fleet Capacity Ceilings (Art. 22)",
            "status": "INHERITED & REFORMED",
            "note": "Capacity limits existed since 1992 (MAGP IV) and were continued under Reg. 2371/2002. The 2013 reform maintained the ceiling concept but replaced the entry-exit scheme with a simpler maximum reference level per Member State."
          },
          {
            "element": "Multiannual Plans (Art. 9-11)",
            "status": "INHERITED & REFORMED",
            "note": "Long-term management plans existed under the 2002 CFP but were narrow in scope. The 2013 regulation broadened them to multi-species, ecosystem-based plans and linked them to the MSY obligation."
          }
        ]
      },
      "briefing": "The Common Fisheries Policy reform of 2013 was the EU's most ambitious attempt to reconcile fisheries exploitation with ecological sustainability. Its twin pillars — the legally binding MSY target and the landing obligation — represented a genuine break from predecessor frameworks that tolerated overfishing and normalised discarding. The regionalisation mechanism addressed the longstanding democratic deficit by giving Member States a structured role in shaping conservation rules for their own waters. On paper, Reg. 1380/2013 is one of the strongest fisheries governance frameworks globally.\n\nIn practice, implementation has exposed structural contradictions. The landing obligation collides with the quota system it was layered onto, creating choke species problems that neither de minimis exemptions nor inter-species flexibility have resolved. The MSY target was missed for numerous stocks by the 2020 deadline, with the 'where possible and practicable' qualifier providing indefinite cover. Scientific advice remains advisory in effect — the Council's pattern of setting TACs above ICES recommendations continues. The small-scale fleet priority in Article 17 has not translated into meaningful reallocation of fishing opportunities.\n\nWhat to watch: the next CFP review cycle (expected post-2027) will likely address landing obligation implementation failures, the choke species problem, and climate-driven stock redistribution — an issue the 2013 regulation did not anticipate at all. The revised Control Regulation (2023) introduces mandatory electronic monitoring that could finally make the landing obligation enforceable. Brexit's disruption of shared-stock management in the North-East Atlantic adds a new dimension of uncertainty that the CFP's external dimension provisions were not designed to handle."
    }
  },
  {
    "id": "green_deal",
    "title": "European Green Deal (COM(2019) 640)",
    "domain": "CLIMATE & ENVIRONMENT",
    "classification": "EU COMMUNICATION",
    "preloaded": {
      "decode": {
        "who": [
          "All EU Member States and their national administrations",
          "European industry and energy sector",
          "Agricultural producers and food system actors",
          "Transport operators and vehicle manufacturers",
          "Citizens and consumers across the EU"
        ],
        "what": "The European Green Deal is the EU's overarching strategy to transform the European economy for climate neutrality by 2050. It is not a single binding regulation but a policy communication that launched a legislative programme of over 50 initiatives across energy, transport, industry, agriculture, biodiversity, and finance. The Green Deal reframes climate policy from a narrow environmental issue to the central organising principle of EU economic governance. It established the political mandate for the European Climate Law, the Fit for 55 package, the Nature Restoration Law, the Carbon Border Adjustment Mechanism, and the Social Climate Fund, among others.",
        "scope": "Economy-wide. Covers all sectors contributing to greenhouse gas emissions: energy production and consumption, transport, buildings, industry, agriculture and land use, and waste. Extends to biodiversity and ecosystem protection, circular economy, pollution reduction, and sustainable finance. Also addresses the external dimension — trade policy, international climate diplomacy, and development cooperation.",
        "keyDefinitions": [
          {
            "term": "Climate Neutrality",
            "definition": "Net-zero greenhouse gas emissions by 2050. Residual emissions must be balanced by removals (natural sinks or technological solutions). Enshrined as a binding target in the European Climate Law (Reg. 2021/1119)."
          },
          {
            "term": "Fit for 55",
            "definition": "The legislative package implementing the Green Deal's intermediate target of at least 55% net GHG reduction by 2030 compared to 1990. Comprises revisions to the ETS, Effort Sharing Regulation, LULUCF, renewable energy and energy efficiency directives, and new instruments like CBAM and the Social Climate Fund."
          },
          {
            "term": "Just Transition",
            "definition": "The principle that the green transition must not leave anyone behind. Supported by the Just Transition Mechanism (EUR 55bn), including the Just Transition Fund targeting regions most dependent on fossil fuels and carbon-intensive industries."
          },
          {
            "term": "Carbon Border Adjustment Mechanism (CBAM)",
            "definition": "A levy on imports of carbon-intensive goods (steel, cement, aluminium, fertilisers, electricity, hydrogen) to prevent carbon leakage — the relocation of production to countries with weaker climate policies. Transitional phase began October 2023; full implementation from 2026."
          },
          {
            "term": "Do No Significant Harm (DNSH)",
            "definition": "A principle from the EU Taxonomy Regulation requiring that economic activities claimed as 'sustainable' must not significantly harm any of six environmental objectives: climate mitigation, climate adaptation, water, circular economy, pollution, and biodiversity."
          }
        ]
      },
      "timeline": [
        {
          "date": "2019-12-11",
          "event": "European Green Deal Communication published (COM(2019) 640)",
          "type": "milestone"
        },
        {
          "date": "2020-03",
          "event": "European Climate Law proposal tabled (climate neutrality by 2050)",
          "type": "milestone"
        },
        {
          "date": "2021-06-30",
          "event": "European Climate Law adopted (Reg. 2021/1119) — binding 2050 target and 55% by 2030",
          "type": "milestone"
        },
        {
          "date": "2021-07-14",
          "event": "Fit for 55 legislative package published (13 interconnected proposals)",
          "type": "milestone"
        },
        {
          "date": "2023-10-01",
          "event": "CBAM transitional phase begins — importers start reporting embedded emissions",
          "type": "obligation"
        },
        {
          "date": "2026-01-01",
          "event": "CBAM fully operational — financial adjustment on imports begins",
          "type": "deadline"
        },
        {
          "date": "2027",
          "event": "ETS2 launches — carbon pricing for buildings and road transport",
          "type": "deadline"
        },
        {
          "date": "2030",
          "event": "Intermediate target: at least 55% net GHG reduction vs 1990",
          "type": "deadline"
        },
        {
          "date": "2050",
          "event": "Climate neutrality target — net-zero GHG emissions across the EU",
          "type": "deadline"
        }
      ],
      "deepDive": {
        "ambiguities": [
          {
            "text": "leaving no one behind",
            "analysis": "The Just Transition pledge is central to the Green Deal's political narrative but lacks enforceable criteria. What constitutes being 'left behind'? Income loss? Job loss? Energy cost increase above a threshold? Without binding metrics, the promise is a political commitment with no legal teeth."
          },
          {
            "text": "at least 55%",
            "analysis": "The 2030 target is 'at least' 55% net GHG reduction, deliberately leaving upward ambiguity. This has sparked continuous pressure from the European Parliament (which voted for 60%) and environmental groups. The qualifier creates a moving target that undermines investment certainty for long-cycle capital decisions."
          },
          {
            "text": "sustainable activity",
            "analysis": "Despite the Taxonomy Regulation's detailed criteria, the political inclusion of natural gas and nuclear energy as 'transitional' sustainable activities (Delegated Act 2022/1214) demonstrated that the definition of 'sustainable' remains politically negotiable. This undermines the taxonomy's credibility as an objective classification."
          },
          {
            "text": "cost-effective pathway",
            "analysis": "The Green Deal commits to a 'cost-effective' transition but cost-effectiveness is assessed differently depending on the discount rate, time horizon, and whether externalities are included. A pathway that is cost-effective over 30 years may impose severe short-term costs on specific sectors — the framing obscures distributional pain."
          }
        ],
        "contradictions": [
          {
            "issue": "Growth Narrative vs. Absolute Emissions Reduction",
            "detail": "The Green Deal explicitly aims to 'decouple economic growth from resource use.' But much of its legislative programme (CBAM, renewable energy targets, renovation wave) assumes continued GDP growth alongside decarbonisation. Whether absolute decoupling at the required speed is physically possible remains deeply contested in climate science. The Green Deal avoids engaging with degrowth arguments entirely."
          },
          {
            "issue": "Agricultural Ambition vs. CAP Continuity",
            "detail": "The Farm to Fork Strategy (part of the Green Deal) proposed 50% pesticide reduction, 20% fertiliser reduction, and 25% organic farming by 2030. But the Common Agricultural Policy (2023-2027) was negotiated simultaneously with weaker conditionality than these targets require. Two legislative tracks pulling in opposite directions on the same sector."
          },
          {
            "issue": "Trade Openness vs. Carbon Ambition",
            "detail": "CBAM addresses carbon leakage for imported goods, but the EU simultaneously pursues free trade agreements (Mercosur, New Zealand) that increase imports of agricultural products produced with lower environmental standards. The trade policy arm of the EU does not always reflect the climate ambition of the Green Deal."
          }
        ],
        "stakeholderImpacts": [
          {
            "group": "Energy-intensive industries (steel, cement, chemicals)",
            "impact": "EXISTENTIAL TRANSFORMATION",
            "detail": "Must decarbonise processes that have been carbon-intensive for over a century. Free ETS allowances phase out by 2034 as CBAM phases in. The transition requires tens of billions in investment with uncertain payback timelines. Some production may relocate despite CBAM."
          },
          {
            "group": "Fossil-fuel dependent regions (coal regions)",
            "impact": "MANAGED DECLINE",
            "detail": "The Just Transition Fund provides EUR 17.5bn, but regions like Silesia (Poland), Western Macedonia (Greece), and the Ruhr face loss of entire economic identities. Fund scale is modest relative to the economic shock of closing coal mines and coal-fired plants."
          },
          {
            "group": "Renewable energy developers",
            "impact": "MASSIVE GROWTH OPPORTUNITY",
            "detail": "The revised Renewable Energy Directive (RED III) targets 42.5% renewable share by 2030. Permitting acceleration measures (REPowerEU) accelerate deployment. Sector faces a demand boom constrained by supply chain bottlenecks, grid capacity, and workforce shortages."
          },
          {
            "group": "EU farmers",
            "impact": "SQUEEZED BETWEEN AMBITION AND REALITY",
            "detail": "Farm to Fork targets would reduce input use while maintaining food production. Farmer protests (2023-2024) across Belgium, France, Germany, and Poland have already forced political retreat on pesticide reduction legislation."
          },
          {
            "group": "Low-income households",
            "impact": "TRANSITION COST EXPOSURE",
            "detail": "ETS2 will raise heating and transport costs from 2027. The Social Climate Fund (EUR 65bn) is intended to cushion the blow but structural timing mismatch means costs arrive before investments pay off."
          }
        ],
        "crossReferences": [
          {
            "regulation": "Regulation (EU) 2021/1119 — European Climate Law",
            "relation": "Translates the Green Deal's political commitment into binding law. Establishes 2050 climate neutrality and the 2030 -55% target as legally enforceable obligations. All EU institutions and Member States must ensure consistency with these targets."
          },
          {
            "regulation": "Regulation (EU) 2023/956 — Carbon Border Adjustment Mechanism (CBAM)",
            "relation": "Implements the Green Deal's 'no carbon leakage' principle. Applies to imports of iron/steel, cement, aluminium, fertilisers, electricity, and hydrogen. Prices imported carbon at the EU ETS rate."
          },
          {
            "regulation": "Regulation (EU) 2023/955 — Social Climate Fund",
            "relation": "The Green Deal's primary social compensation mechanism. EUR 65bn to support vulnerable households, micro-enterprises, and transport users affected by ETS2 carbon pricing."
          },
          {
            "regulation": "Regulation (EU) 2020/852 — Taxonomy Regulation",
            "relation": "Defines what counts as an environmentally sustainable economic activity. Underpins the Green Deal's sustainable finance agenda by providing a classification system for investors, companies, and policymakers."
          },
          {
            "regulation": "Regulation (EU) 2024/1991 — Nature Restoration Law",
            "relation": "Implements the Green Deal's biodiversity targets. Requires Member States to restore at least 20% of EU land and sea areas by 2030, with binding national restoration plans."
          }
        ],
        "newVsInherited": [
          {
            "element": "2050 Climate Neutrality Target",
            "status": "NEW",
            "note": "No predecessor EU framework contained a binding net-zero target. The 2030 Climate and Energy Framework had emission reduction targets but climate neutrality as a legal obligation is entirely new."
          },
          {
            "element": "Carbon Border Adjustment (CBAM)",
            "status": "NEW",
            "note": "First-ever border carbon pricing mechanism by a major economy. Replaces the previous reliance on free ETS allowances to prevent carbon leakage — a fundamentally different approach."
          },
          {
            "element": "Emissions Trading System (ETS)",
            "status": "INHERITED & REFORMED",
            "note": "The EU ETS has operated since 2005 (Phase I). The Green Deal reformed it significantly: tighter cap, expanded scope to maritime, and created ETS2 for buildings and transport. The instrument is inherited but its ambition level and scope are transformed."
          },
          {
            "element": "Renewable Energy Targets",
            "status": "STRENGTHENED",
            "note": "Renewable energy targets have existed since Directive 2001/77/EC and were raised in RED I (2009) and RED II (2018). RED III (2023) increases the target to 42.5% by 2030. The obligation is inherited; the ambition level is significantly strengthened."
          },
          {
            "element": "Social Climate Fund / Just Transition Fund",
            "status": "NEW",
            "note": "Dedicated social compensation instruments linked to climate policy are entirely new. Previous EU climate legislation did not include structured mechanisms to cushion distributional impacts on vulnerable groups."
          },
          {
            "element": "Energy Efficiency Obligation (Art. 7, EED)",
            "status": "INHERITED & REFORMED",
            "note": "Energy efficiency targets date back to the 2006 Action Plan and became binding under the 2012 EED. The recast 2023 EED raised ambition to 11.7% reduction in final energy consumption by 2030 and added energy poverty provisions."
          }
        ]
      },
      "briefing": "The European Green Deal is the most comprehensive attempt by any major economy to legislate economy-wide decarbonisation. Its strength lies in systemic scope: rather than isolated climate policies, it restructures energy, transport, agriculture, industry, trade, and finance around a single 2050 net-zero target now enshrined in binding law. The legislative output has been extraordinary — over 50 initiatives in five years, including globally unprecedented instruments like CBAM and the Social Climate Fund.\n\nThe structural tensions are equally significant. The Green Deal promises continued economic growth through green decoupling — a proposition that is optimistic at best for the speed and scale required. Agricultural ambition (Farm to Fork) has already retreated under political pressure from farmer protests. The social dimension (Just Transition, Social Climate Fund) is real but undersized relative to the distributional shock that carbon pricing in buildings and transport will create from 2027. The inclusion of gas and nuclear in the taxonomy damaged credibility. And the simultaneous pursuit of trade liberalisation and climate ambition creates unresolved contradictions.\n\nWhat to watch: the 2030 target delivery gap (current policies project roughly 50%, not 55%), the political fallout when ETS2 raises heating and fuel costs, CBAM implementation challenges with trading partners (especially China, Turkey, India), and whether the nature restoration targets survive the backlash that has already delayed the Pesticides Regulation. The Green Deal's legacy will be determined not by its legislative ambition — which is impressive — but by whether implementation survives the political costs of actual transformation."
    }
  },
  {
    "id": "ai_act",
    "title": "EU AI Act (Reg. 2024/1689)",
    "domain": "DIGITAL & TECHNOLOGY",
    "classification": "EU REGULATION",
    "preloaded": {
      "decode": {
        "who": [
          "AI system providers (developers and companies placing AI on the EU market)",
          "Deployers (organisations using AI systems in the EU)",
          "National market surveillance authorities",
          "Individuals affected by AI decisions (citizens, workers, consumers)",
          "General-purpose AI (GPAI) model providers including foundation model developers"
        ],
        "what": "The EU AI Act is the world's first comprehensive legal framework for artificial intelligence. It establishes a risk-based classification system: unacceptable-risk AI is banned outright, high-risk AI must meet stringent requirements before market placement, limited-risk AI faces transparency obligations, and minimal-risk AI is unregulated. The regulation also introduces specific rules for general-purpose AI models, including transparency requirements for all GPAI and additional obligations for models with systemic risk. It creates a new EU AI Office within the Commission to oversee enforcement of GPAI rules.",
        "scope": "Applies to providers placing AI systems on the EU market regardless of their establishment, deployers of AI systems within the EU, and providers and deployers in third countries whose AI output is used in the EU. Excludes AI for purely military or defence purposes, AI used exclusively for scientific research and development, and AI systems released under free and open-source licences (with exceptions for high-risk and GPAI with systemic risk).",
        "keyDefinitions": [
          {
            "term": "AI System",
            "definition": "A machine-based system designed to operate with varying levels of autonomy, that may exhibit adaptiveness after deployment and that, for explicit or implicit objectives, infers from inputs it receives how to generate outputs such as predictions, content, recommendations, or decisions that can influence physical or virtual environments. Aligned with the OECD AI definition."
          },
          {
            "term": "High-Risk AI System",
            "definition": "An AI system listed in Annex III (covering biometrics, critical infrastructure, education, employment, essential services, law enforcement, migration, and justice) or used as a safety component of a product covered by EU product safety legislation listed in Annex I. Subject to mandatory conformity assessment, risk management, data governance, and human oversight requirements."
          },
          {
            "term": "General-Purpose AI (GPAI) Model",
            "definition": "An AI model trained with a large amount of data using self-supervision at scale, that displays significant generality and is capable of competently performing a wide range of distinct tasks. Includes foundation models and large language models."
          },
          {
            "term": "Systemic Risk",
            "definition": "Risk specific to GPAI models with high-impact capabilities. Presumed when cumulative training compute exceeds 10^25 FLOP, or designated by the Commission based on other criteria. Triggers additional obligations including adversarial testing, incident reporting, and cybersecurity protections."
          },
          {
            "term": "Deployer",
            "definition": "Any natural or legal person using an AI system under its authority, except where the AI is used in the course of a personal non-professional activity. Deployers have obligations distinct from providers — primarily focused on use-context compliance, human oversight, and transparency to affected persons."
          },
          {
            "term": "Conformity Assessment",
            "definition": "The process of verifying that a high-risk AI system meets all applicable requirements before it can be placed on the market. May be self-assessed (for most categories) or require third-party notified body assessment (for biometric identification systems)."
          }
        ]
      },
      "timeline": [
        {
          "date": "2021-04-21",
          "event": "Commission publishes original AI Act proposal (COM(2021) 206)",
          "type": "milestone"
        },
        {
          "date": "2023-06-14",
          "event": "European Parliament adopts negotiating position (including GPAI provisions)",
          "type": "milestone"
        },
        {
          "date": "2023-12-08",
          "event": "Political agreement reached in trilogue negotiations",
          "type": "milestone"
        },
        {
          "date": "2024-07-12",
          "event": "Regulation (EU) 2024/1689 published in the Official Journal",
          "type": "milestone"
        },
        {
          "date": "2025-02-02",
          "event": "Prohibitions on unacceptable-risk AI practices enter into force",
          "type": "deadline"
        },
        {
          "date": "2025-08-02",
          "event": "GPAI model obligations apply — transparency and systemic risk rules",
          "type": "obligation"
        },
        {
          "date": "2026-08-02",
          "event": "High-risk AI system requirements fully apply (Annex III categories)",
          "type": "deadline"
        },
        {
          "date": "2027-08-02",
          "event": "Obligations for high-risk AI in Annex I product safety legislation apply",
          "type": "deadline"
        }
      ],
      "deepDive": {
        "ambiguities": [
          {
            "text": "varying levels of autonomy",
            "analysis": "The definition of AI system includes systems operating with 'varying levels of autonomy.' This is deliberately broad but creates boundary problems. A complex rule-based system with adaptive thresholds could qualify, while a simple neural network might not feel 'autonomous.' The line between traditional software and regulated AI is unclear and will generate significant interpretive litigation."
          },
          {
            "text": "meaningful human oversight",
            "analysis": "High-risk AI systems must allow effective human oversight. But what counts as 'meaningful'? A human clicking 'approve' on 500 AI recommendations per hour is technically oversight but practically rubber-stamping. The regulation requires that humans can 'understand the capabilities and limitations' of the AI — a standard that may be unachievable for complex models even by technical experts."
          },
          {
            "text": "significant generality",
            "analysis": "GPAI models are defined as showing 'significant generality' across tasks. Where is the threshold? A model fine-tuned for three related tasks is less general than GPT-4, but more general than a single-purpose classifier. The distinction between a specialized AI and a GPAI model is a spectrum, not a line."
          },
          {
            "text": "state of the art",
            "analysis": "Several provisions require risk management and testing measures reflecting the 'state of the art.' In a field where capabilities change monthly, today's state of the art is tomorrow's baseline. This creates a moving compliance target that may be burdensome for providers to track and for regulators to verify."
          }
        ],
        "contradictions": [
          {
            "issue": "Innovation vs. Precaution",
            "detail": "The regulation simultaneously aims to 'promote the uptake of AI' and impose strict ex-ante requirements on high-risk systems. Conformity assessment, mandatory documentation, and registration requirements create compliance costs that disproportionately burden startups and SMEs. The regulation includes SME-friendly provisions (sandboxes, reduced fees) but the structural burden remains — a startup deploying a high-risk system faces the same substantive requirements as a large enterprise."
          },
          {
            "issue": "Open-Source Exemption vs. Risk Logic",
            "detail": "Free and open-source AI systems are largely exempt from the regulation (except for prohibited practices and GPAI with systemic risk). But the risk a system poses to individuals depends on how it is deployed, not on its licensing model. An open-source model used for high-risk recruitment screening poses the same risk as a proprietary one. The exemption is policy-motivated (not harming open source) but logically inconsistent with a risk-based framework."
          },
          {
            "issue": "GPAI Compute Threshold vs. Rapid Capability Growth",
            "detail": "Systemic risk is presumed at 10^25 FLOP of training compute. This threshold was calibrated to capture GPT-4-class models at the time of negotiation. But training efficiency improves rapidly — future models may achieve equivalent or greater capabilities at far less compute. A fixed compute threshold becomes increasingly disconnected from actual risk over time."
          }
        ],
        "stakeholderImpacts": [
          {
            "group": "Large AI companies (Big Tech, GPAI providers)",
            "impact": "COMPLIANCE COST, MARKET ADVANTAGE",
            "detail": "Substantial compliance investment required — risk management systems, documentation, third-party audits for systemic-risk models. But large firms can absorb these costs, while the regulatory barrier protects their market position against smaller competitors."
          },
          {
            "group": "EU AI startups and SMEs",
            "impact": "DISPROPORTIONATE BURDEN",
            "detail": "Regulatory sandboxes and reduced conformity assessment fees help, but the substantive requirements (documentation, risk management, human oversight design) impose fixed costs that scale poorly for small teams. Risk of EU startups choosing to deploy outside Europe first."
          },
          {
            "group": "Public sector deployers (police, border agencies, courts)",
            "impact": "HEIGHTENED SCRUTINY",
            "detail": "Many Annex III high-risk categories target public sector uses: law enforcement, migration management, justice. Real-time biometric identification is banned in public spaces except for narrowly defined exceptions. Requires fundamental rights impact assessments before deployment."
          },
          {
            "group": "Workers subject to AI management",
            "impact": "NEW PROTECTIONS, ENFORCEMENT UNCERTAIN",
            "detail": "Employment-related AI (recruitment screening, performance monitoring, task allocation) is classified as high-risk. Workers gain transparency and human oversight rights. But enforcement depends on national labour inspectorates that may lack AI technical expertise."
          },
          {
            "group": "Open-source AI community",
            "impact": "LARGELY EXEMPTED, BUT BOUNDARIES UNCLEAR",
            "detail": "Open-source AI benefits from broad exemptions, but GPAI models with systemic risk are not exempt regardless of licence. The boundary between exempt and regulated open-source models will generate controversy as open-source models grow more capable."
          }
        ],
        "crossReferences": [
          {
            "regulation": "GDPR (Regulation 2016/679) — Articles 22 and 35",
            "relation": "Article 22 (automated decision-making) and Article 35 (DPIA) apply in parallel to AI systems processing personal data. Compliance with the AI Act does not exempt from GDPR obligations — creating cumulative requirements with different supervisory authorities."
          },
          {
            "regulation": "Product Safety Regulation (EU) 2023/988",
            "relation": "AI-enabled products must comply with both the AI Act (for the AI component) and product safety legislation (for the physical product). Annex I of the AI Act lists EU product safety directives whose products become high-risk when incorporating AI."
          },
          {
            "regulation": "Proposed AI Liability Directive (COM(2022) 496)",
            "relation": "Would establish civil liability rules specific to AI, including a rebuttable presumption of causality and disclosure obligations for evidence held by AI providers. Currently stalled in legislative process but would complement the AI Act's ex-ante rules with ex-post liability."
          },
          {
            "regulation": "Digital Services Act (Regulation 2022/2065)",
            "relation": "Regulates algorithmic recommender systems on platforms — overlapping with AI Act provisions on transparency. Very large platforms must provide information about recommender system parameters and allow users to modify them."
          },
          {
            "regulation": "Directive 2000/78/EC — Equal Treatment in Employment",
            "relation": "Anti-discrimination law applies independently to AI employment decisions. The AI Act's bias testing requirements for high-risk systems operationalise these existing discrimination prohibitions in the AI context."
          }
        ],
        "newVsInherited": [
          {
            "element": "Risk-Based AI Classification (Title III)",
            "status": "NEW",
            "note": "No predecessor EU legislation classified AI systems by risk level. The four-tier system (unacceptable, high, limited, minimal risk) is an entirely new regulatory architecture without precedent in EU or global law."
          },
          {
            "element": "GPAI Model Rules (Title IIIa)",
            "status": "NEW",
            "note": "Added during negotiations after ChatGPT's launch. Not in the original 2021 Commission proposal. Addresses foundation models and systemic risk — an entirely reactive regulatory innovation driven by real-world developments during the legislative process."
          },
          {
            "element": "Prohibited AI Practices (Art. 5)",
            "status": "NEW",
            "note": "Outright bans on social scoring, manipulative subliminal techniques, exploitation of vulnerabilities, untargeted facial recognition database scraping, and emotion recognition in workplaces and education. First hard prohibitions on specific AI applications globally."
          },
          {
            "element": "CE Marking / Conformity Assessment for AI",
            "status": "INHERITED & REFORMED",
            "note": "The conformity assessment and CE marking framework is borrowed from EU product safety law (New Legislative Framework). The AI Act adapts this well-established mechanism to a fundamentally different type of product — software that evolves post-deployment."
          },
          {
            "element": "Regulatory Sandboxes (Art. 57-62)",
            "status": "NEW",
            "note": "Mandatory establishment of AI regulatory sandboxes by each Member State. While financial services sandboxes existed previously, the AI Act makes sandboxes a structural element of EU AI governance — a first for horizontal EU legislation."
          },
          {
            "element": "Fundamental Rights Impact Assessment (Art. 27)",
            "status": "NEW",
            "note": "Deployers of high-risk AI in public contexts must assess fundamental rights impacts before deployment. Builds on GDPR's DPIA concept but extends the assessment obligation beyond data protection to broader fundamental rights (non-discrimination, human dignity, access to justice)."
          }
        ]
      },
      "briefing": "The EU AI Act is a landmark in global technology regulation — the first comprehensive, binding framework for artificial intelligence anywhere in the world. Its risk-based architecture is intellectually elegant: ban the intolerable, regulate the dangerous, require transparency for the deceptive, and leave the rest alone. The addition of GPAI model rules during trilogue showed the EU's capacity to adapt legislation to a technology moving faster than any regulatory process. The scope is deliberately extraterritorial — any AI system whose output is used in the EU falls under its reach, regardless of where the provider is based.\n\nThe practical challenges are formidable. The definition of 'AI system' is broad enough to potentially capture advanced analytics and adaptive software that providers do not consider AI. The 'meaningful human oversight' requirement is easy to state but hard to operationalise — particularly for systems making hundreds of decisions per second. The GPAI compute threshold (10^25 FLOP) for systemic risk was calibrated to current capabilities but training efficiency improvements will make it outdated. And the tension between the open-source exemption and the risk-based logic is unresolved: risk is a function of deployment context, not licensing model.\n\nWhat to watch: the February 2025 prohibitions (first enforcement test), the August 2025 GPAI compliance deadline (will large model providers comply or contest?), the August 2026 high-risk rules (the real regulatory impact), and the establishment of national market surveillance authorities (most Member States lack dedicated AI regulatory capacity). The AI Act's Brussels Effect potential is high — non-EU AI providers may adopt its standards globally to maintain EU market access, as happened with GDPR. But if enforcement is weak or inconsistent across Member States, the Act risks becoming a paper tiger with impressive provisions and minimal real-world impact."
    }
  }
],
  compare: [
  {
    "id": "cfp_greek",
    "title": "CFP Landing Obligation vs Greek Transposition",
    "doc1Label": "EU Regulation",
    "doc2Label": "Greek National Law",
    "preloaded": {
      "read": {
        "doc1": {
          "title": "Regulation (EU) No 1380/2013 — Common Fisheries Policy, Article 15",
          "type": "EU Regulation",
          "legalBasis": "Art. 43(2) TFEU",
          "scope": "Landing obligation for all EU fishing vessels operating in EU waters and beyond, covering all species subject to catch limits or minimum sizes",
          "articles": 15,
          "date": "2013-12-11"
        },
        "doc2": {
          "title": "Presidential Decree 48/2017 — Implementation of the Landing Obligation in Greek Fisheries",
          "type": "Presidential Decree",
          "legalBasis": "Transposing Reg. 1380/2013 Art. 15",
          "scope": "Greek-flagged vessels in GSAs 20, 22, 23 (Aegean Sea, Ionian Sea, Crete)",
          "articles": 8,
          "date": "2017-06-15"
        }
      },
      "mapping": [
        {
          "doc1Provision": "Art. 15(1) — Landing obligation for all regulated species",
          "doc2Provision": "Art. 3 — Obligation to land all catches of species listed in Annex I",
          "status": "ALIGNED",
          "notes": "The core obligation is faithfully transposed. Both instruments require that all catches of regulated species be retained on board, landed, and counted against quotas. The Greek decree mirrors the EU language closely, establishing a general prohibition on discarding for the listed species. No material divergence in the primary obligation itself."
        },
        {
          "doc1Provision": "Art. 15(2) — Species coverage: all species subject to catch limits or MCRS in each sea basin",
          "doc2Provision": "Art. 3 + Annex I — Species subject to landing obligation as listed in Annex I",
          "status": "PARTIAL",
          "notes": "The EU regulation applies the landing obligation to all species subject to catch limits in the relevant sea basin, with coverage expanding over the phase-in period (2015–2019). The Greek Annex I lists only 23 species, which is narrower than the full EU list for the Mediterranean. Several deep-water species and small pelagics present in Greek waters are omitted from Annex I, creating a partial transposition gap. Fishers targeting unlisted species may not be subject to the landing obligation under national law even where the EU regulation would require it."
        },
        {
          "doc1Provision": "Art. 15(4)(a) — De minimis exemption up to 5% of total annual catches",
          "doc2Provision": "Art. 4 — De minimis exemption set at 3% of total annual catches per species",
          "status": "GOLD-PLATED",
          "notes": "The EU regulation permits Member States to allow discarding of up to 5% of total annual catches of each species where scientific evidence shows that selectivity improvements are very difficult or where handling costs are disproportionate. The Greek decree adopts a stricter 3% threshold. This gold-plating reduces operational flexibility for Greek fishers relative to competitors in other Member States that apply the full 5%. The economic impact falls disproportionately on mixed-species trawl fisheries where incidental catch composition is difficult to control."
        },
        {
          "doc1Provision": "Art. 15(4)(b) — High survivability exemptions for species with demonstrated post-release survival",
          "doc2Provision": null,
          "status": "GAP",
          "notes": "The EU regulation allows exemptions from the landing obligation for species with scientifically demonstrated high survival rates after discarding (e.g. Norway lobster, certain skates and rays). The Greek decree contains no equivalent provision. This is the most critical transposition gap: fishers must land species that could legally be returned alive under EU law, creating unnecessary economic burden (hold space, ice, processing costs) without any ecological benefit. STECF evidence shows survival rates of 40–70% for nephrops in certain Mediterranean trawl fisheries."
        },
        {
          "doc1Provision": "Art. 15(5) — Documentation and reporting: all catches to be recorded in logbook",
          "doc2Provision": "Art. 5 — Mandatory electronic logbook for all vessels exceeding 8m LOA",
          "status": "GOLD-PLATED",
          "notes": "The EU regulation requires recording of all catches but applies mandatory electronic logbooks (ERS) only to vessels over 12m LOA. The Greek decree extends this requirement to vessels over 8m, capturing a significant portion of the small-scale artisanal fleet. While improved data collection has conservation value, the cost of electronic equipment and training disproportionately affects small-scale operators who often fish with low-impact gears and generate minimal bycatch. This represents a policy choice beyond EU requirements."
        },
        {
          "doc1Provision": "Art. 15(6) — Minimum Conservation Reference Sizes (MCRS) as defined in technical measures",
          "doc2Provision": "Art. 2 — Definitions: references Minimum Landing Sizes (MLS) per Reg. 1967/2006 Annex III",
          "status": "DIVERGENT",
          "notes": "This is a terminological and substantive divergence. The EU framework replaced the concept of Minimum Landing Sizes (MLS) with Minimum Conservation Reference Sizes (MCRS) under the 2013 CFP reform and the 2019 Technical Measures Regulation (2019/1241). MCRS serves a different purpose: under the landing obligation, fish below MCRS must still be landed but cannot be sold for direct human consumption. The Greek decree still references MLS values from the old Mediterranean Regulation (1967/2006), which creates legal confusion about which size thresholds apply and what happens to undersized catches. Some MLS and MCRS values differ for the same species."
        },
        {
          "doc1Provision": "Art. 15(7) — Inter-species quota flexibility: up to 9% of quota for one species may be counted against another",
          "doc2Provision": null,
          "status": "GAP",
          "notes": "The EU regulation provides a mechanism for inter-species flexibility, allowing up to 9% of a quota for one species to be deducted from the quota of another species in the same functional unit, provided the stock of the second species is within safe biological limits. This is a critical tool for mixed fisheries where species are caught together and quota uptake rates differ. The Greek decree contains no equivalent provision, removing an important flexibility mechanism for fishers operating in the highly mixed-species demersal fisheries of the Aegean."
        },
        {
          "doc1Provision": "Art. 15(8) — Prior notification of landing: advance notice to port authorities",
          "doc2Provision": "Art. 6(2) — 4-hour advance notice to the designated port authority before landing",
          "status": "ALIGNED",
          "notes": "Both instruments require advance notification before landing. The Greek decree specifies a 4-hour notice period, which is consistent with the general EU control framework (Reg. 1224/2009). The EU landing obligation provision itself does not set a specific timeframe, deferring to the control regulation. The Greek implementation is well aligned and operationally practical for the relatively short trip durations typical of Greek fisheries."
        },
        {
          "doc1Provision": "Art. 15(9) — Link to multiannual plans: landing obligation details to be specified in regional multiannual management plans",
          "doc2Provision": null,
          "status": "GAP",
          "notes": "The EU regulation envisages that the details of the landing obligation (species lists, exemptions, de minimis levels) would be refined through regional multiannual plans developed jointly by Member States with a direct management interest. The Greek decree was drafted in isolation without referencing the Western Mediterranean MAP (Reg. 2019/982) or the GFCM framework. This means the national transposition is not dynamically linked to evolving regional management measures and may become outdated as multiannual plans introduce new requirements or modify exemption conditions."
        },
        {
          "doc1Provision": null,
          "doc2Provision": "Art. 7 — Penalties: fines of EUR 1,000 to 50,000 based on infringement severity, vessel size, and repeat offence status",
          "status": "NATIONAL ADDITION",
          "notes": "The EU regulation does not specify penalty levels for non-compliance with the landing obligation, leaving enforcement and sanctions to Member States under the general fisheries control framework (Reg. 1224/2009). The Greek decree introduces a specific penalty schedule with fines ranging from EUR 1,000 (minor first offence) to EUR 50,000 (serious repeated violations). The schedule is graduated by vessel size category and includes provisions for licence suspension on third offence. This is a legitimate national addition that provides legal certainty for enforcement authorities and deterrence for non-compliance."
        }
      ],
      "gapAnalysis": {
        "transpositionGaps": [
          {
            "provision": "High survivability exemptions (Art. 15(4)(b))",
            "severity": "HIGH",
            "detail": "The EU regulation allows exemptions from the landing obligation for species with scientifically demonstrated high post-release survival rates. The Greek decree omits this entirely. This forces fishers to land species like nephrops and certain skates that could legally be returned alive, creating unnecessary economic burden (hold space, ice, processing costs for unsaleable catches) without ecological benefit. STECF survival studies indicate 40–70% post-discard survival for nephrops in Mediterranean trawl fisheries. Priority: HIGH — requires immediate amendment to avoid unjustified economic harm to the fleet."
          },
          {
            "provision": "Inter-species quota flexibility (Art. 15(7))",
            "severity": "MEDIUM",
            "detail": "The EU regulation permits up to 9% inter-species flexibility for quota deductions in mixed fisheries. This mechanism is absent from the Greek decree. In the Aegean’s highly mixed demersal fisheries, where trawls routinely catch 10–15 species simultaneously, the lack of inter-species flexibility creates a rigid system where quota exhaustion for a single choke species can halt an entire fishery. This undermines the economic viability of mixed-species operations and may incentivise illegal discarding."
          },
          {
            "provision": "Multiannual plan linkage (Art. 15(9))",
            "severity": "MEDIUM",
            "detail": "The EU framework requires that landing obligation details be specified and updated through regional multiannual management plans. The Greek decree was drafted as a static instrument with no mechanism for automatic incorporation of evolving regional measures. As the Western Mediterranean MAP (Reg. 2019/982) and GFCM recommendations introduce new requirements, the national transposition risks becoming outdated without formal amendment procedures. This structural gap will worsen over time."
          }
        ],
        "goldPlating": [
          {
            "provision": "De minimis threshold (Art. 4: 3% vs EU 5%)",
            "detail": "The Greek decree sets the de minimis discard exemption at 3% of total annual catches per species, compared to the EU maximum of 5%. This imposes a stricter regime on Greek fishers than their counterparts in other Mediterranean Member States (Italy, Spain, France) who can apply the full 5%. The economic impact falls disproportionately on small-scale trawl and trammel net fisheries where bycatch composition is difficult to control. No scientific justification for the lower threshold is provided in the decree’s preamble."
          },
          {
            "provision": "Electronic logbook requirement (Art. 5: >8m vs EU >12m)",
            "detail": "The EU control framework (Reg. 1224/2009) mandates electronic logbooks (ERS) for vessels over 12m LOA. The Greek decree extends this to vessels over 8m, capturing a substantial proportion of the artisanal fleet. Equipment costs (€800–1,500 per unit) and training requirements represent a significant burden for small-scale fishers whose annual revenue may be under €15,000. While improved catch data has conservation value, the proportionality of this measure is questionable for low-impact coastal operations."
          }
        ],
        "contradictions": [
          {
            "provision": "Minimum size references: MCRS vs MLS (Art. 2 definitions)",
            "detail": "The Greek decree’s definitions article references Minimum Landing Sizes (MLS) from the old Mediterranean Regulation (1967/2006 Annex III), despite the EU having replaced MLS with Minimum Conservation Reference Sizes (MCRS) under the 2013 CFP reform and the 2019 Technical Measures Regulation (2019/1241). This is not merely a terminological issue: MCRS and MLS serve different legal purposes. Under MLS, undersized fish could not be landed at all; under MCRS, they must be landed but restricted to non-human consumption. The decree’s use of the old terminology creates ambiguity about the legal treatment of undersized catches and may lead to enforcement inconsistencies. For at least three species (hake, red mullet, anchovy), the old MLS values differ from current MCRS values, compounding the confusion."
          }
        ],
        "nationalAdditions": [
          {
            "provision": "Penalty schedule (Art. 7: EUR 1,000–50,000)",
            "detail": "The decree introduces a graduated penalty framework for landing obligation violations, ranging from EUR 1,000 for minor first offences to EUR 50,000 for serious repeated violations. Fines are calibrated by vessel size category (<12m, 12–24m, >24m) and include licence suspension provisions for third offences. While not required by the EU regulation itself, this fills a gap in the enforcement framework and provides legal certainty. The penalty levels appear proportionate relative to comparable national fisheries penalties in Greece."
          },
          {
            "provision": "Annual fleet inspection target (Art. 6(1): 10% of active vessels)",
            "detail": "The decree establishes a minimum annual inspection target of 10% of active fishing vessels in each GSA for compliance with the landing obligation. The EU control regulation (1224/2009) sets risk-based inspection benchmarks but does not prescribe a specific percentage target for landing obligation compliance. The 10% target provides a clear operational benchmark for the Hellenic Coast Guard and port inspectors, though enforcement capacity remains a challenge given the geographical dispersion of Greek fishing ports across island and mainland communities."
          }
        ]
      },
      "briefing": "Greece’s transposition of the landing obligation is structurally complete but contains significant issues that undermine both legal coherence and operational fairness. The most critical gap is the omission of high survivability exemptions — this forces fishers to land species that could legally be returned alive under EU law, creating unnecessary economic burden without ecological benefit. STECF evidence demonstrates survival rates of 40–70% for nephrops in certain Mediterranean trawl fisheries, making the omission scientifically unjustifiable.\n\nThe gold-plating on de minimis (3% vs 5%) and electronic logbook requirements (>8m vs >12m) imposes costs beyond what the EU requires, potentially disadvantaging Greek fishers relative to competitors in Italy, Spain, and France who operate under the standard EU thresholds. No scientific or policy justification is provided in the decree’s preamble for these stricter standards. The continued use of old MLS terminology instead of MCRS creates genuine legal confusion about the treatment of undersized catches and may lead to enforcement inconsistencies across ports.\n\nThe absence of inter-species quota flexibility and multiannual plan linkage suggests the transposition was drafted in isolation from the broader CFP architecture, treating Article 15 as a standalone obligation rather than part of an integrated fisheries management system. Priority fix: align definitions with the current technical measures framework (Reg. 2019/1241), add the high survivability exemption provision, and establish a mechanism for incorporating future multiannual plan requirements without requiring full legislative amendment."
    }
  }
]
};
